;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-sexp
	backward-up-list
	beginning-of-visual-line
	comment-dwim
	dabbrev-completion
	delete-indentation
	end-of-visual-line
	ergoemacs-M-o
	ergoemacs-backward-block
	ergoemacs-copy-line-or-region
	ergoemacs-cut-line-or-region
	ergoemacs-kill-line-backward
	ergoemacs-shrink-whitespaces
	ergoemacs-toggle-letter-case
	forward-block
	forward-sexp
	indent-for-tab-command
	kill-line-backward
	kill-region
	kill-sexp
	mark-sexp
	nxml-electric-slash
	paredit-backward
	paredit-backward-kill-word
	paredit-backward-up
	paredit-doublequote
	paredit-forward
	paredit-forward-delete
	paredit-forward-kill-word
	paredit-forward-slurp-sexp
	paredit-kill
	paredit-open-round
	paredit-wrap-round
	shrink-whitespaces
	sp-backward-sexp
	sp-forward-sexp
	toggle-letter-case
	yas-expand
	zane/smarter-move-beginning-of-line
	zane/toggle-identifier-case-word-at-point
	))

(setq mc/cmds-to-run-once
      '(
	smex
	))
