;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple
;; cursors.

(setq mc/cmds-to-run-for-all
      '(
        backward-sexp
        beginning-of-visual-line
        dabbrev-completion
        end-of-visual-line
        forward-block
        forward-sexp
        indent-for-tab-command
        kill-region
        kill-sexp
        mark-sexp
        nxml-electric-slash
        paredit-backward
        paredit-backward-kill-word
        paredit-backward-up
        paredit-forward
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-open-round
        shrink-whitespaces
        toggle-letter-case
        yas-expand
        zane/smarter-move-beginning-of-line
        zane/toggle-identifier-case-word-at-point
        ))

(setq mc/cmds-to-run-once
      '(
        smex
        ))
