(add-to-list 'load-path (concat zane-emacs-root "../emacs-color-theme-solarized.github.sellout"))
(require 'solarized-dark-theme)
(require 'solarized-light-theme)
(enable-theme 'solarized-dark)
(show-paren-mode -1)
(fringe-mode -1)
